Dns 37 экран входа по биометрии
surfstudio/dns-flutter pull request #4
Opened 2020-10-01 00:47 UTC by Evoswork

Изменил в MainActivity Android проекта FlutterActivity на FlutterFragmentActivity для работы плагина local_auth. Добавил сообщение в системный диалог touch биометрии для андроида. Приложение сохраняет тип биометрии и её активацию.
п.с. ПР туда смотрит?
![Screenshot at Oct 01 03-45-07](https://user-images.githubusercontent.com/66563284/94753978-98e52b00-0398-11eb-9ecf-21cbe701c725.png)
![Screenshot at Oct 01 03-45-36](https://user-images.githubusercontent.com/66563284/94753991-a5698380-0398-11eb-8d9f-f263954b38ac.png)

2020-10-01 08:52 UTC, artem-zaitsev commented
конфликты

2020-10-01 08:56 UTC, knightsforce commented on app_features/lib/auth/biometric/biometric_interactor.dart
> +    _biometricPreferences.setString(
Используй setBool.

2020-10-01 08:56 UTC, knightsforce commented on app_features/lib/auth/biometric/biometric_interactor.dart
> +      return null;
Верни PermittedBiometricType.none.

2020-10-01 08:56 UTC, knightsforce commented on app_features/lib/auth/biometric/biometric_interactor.dart
> +    return null;
PermittedBiometricType.none.

2020-10-01 08:56 UTC, knightsforce commented on app_features/lib/auth/pin/biometric/biometric_screen.dart
> +      body: Container(
Контейнер нужен?

2020-10-01 08:56 UTC, knightsforce commented on app_features/lib/auth/pin/biometric/biometric_screen.dart
> +    return Container(
Может SizedBox?

2020-10-01 08:56 UTC, knightsforce commented on app_features/lib/auth/pin/biometric/biometric_screen.dart
> +  Widget _bodyBuilder() {
Объяви переменную biometric == PermittedBiometricType.faceID и передавай в методы.

2020-10-01 08:56 UTC, knightsforce commented on app_features/lib/auth/pin/biometric/biometric_wm.dart
> +      (_) async {
Вынеси из onBind в метод.

2020-10-01 08:57 UTC, artem-zaitsev requested changes

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/assignments/lib/domain/collect/interactors/collect_task_interactor.dart
> +    result.data.lines.removeWhere((line) => resultLineList.any((resultLine) => resultLine.key == line.scaffoldKey));
Зачем потребовалось делать исправления в не нашем коде?

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/assignments/lib/domain/service_provision/interactors/service_provision_task_interactor.dart
> +    serviceResult.data.lines.removeWhere((line) => serviceLineList.any((resultLine) => resultLine.key == line.scaffoldKey));
тот же вопрос

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/auth/pin/biometric/biometric_manager.dart
> +      /// todo: Нужно подобрать опд iOS сообщения на touch
Напиши нейтральный текст

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/auth/pin/biometric/biometric_manager.dart
> +        fingerprintHint: STRING_EMPTY,
Обчно испольщовали empty_string

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/auth/pin/biometric/biometric_manager.dart
> +        fingerprintHint: STRING_EMPTY,
А, это коснтанта ДНС, ок

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/auth/pin/biometric/biometric_screen.dart
> +import 'biometric_wm.dart';
импорты должны быть абсолютные

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/auth/pin/biometric/biometric_screen.dart
> +  @override
отступ

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/auth/pin/biometric/biometric_screen.dart
> +          onPressed: () => Navigator.of(context).pop(),
давайте все же не уподобляться плохому коду и работать с навигацией из WM

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/auth/pin/biometric/biometric_screen.dart
> +        child: Text('error'),
в чем проблема?

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/auth/pin/biometric/biometric_screen.dart
> +        child: Text('error'),
Поставь тут некоторый текст на сам экран

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/auth/pin/biometric/biometric_wm.dart
> +        .content(await _biometricManager.getDeviceBiometricType());
давай trailing comma в конце

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/auth/pin/biometric/biometric_wm.dart
> +        .content(await _biometricManager.getDeviceBiometricType());
и могут быть в этой фьюче ошибки?

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/auth/pin/biometric/biometric_wm.dart
> +          await _biometricManager.saveBiometric(
если будут ошибки - ты их не отловишь.

Тут лучше в doFuture обернуть

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/resources/strings.dart
> +const String STRING_SPACE = ' ';
Хорошая идея

2020-10-01 08:57 UTC, artem-zaitsev commented on app_features/lib/resources/text_style.dart
> +/// Стили текстов
тоже хорошл

2020-10-02 10:12 UTC, knightsforce commented on android/app/src/main/kotlin/com/dnsriteil/mobilewebsales/MainActivity.kt
> -class MainActivity : FlutterActivity() {
test

2020-10-02 10:14 UTC, knightsforce commented on app_features/lib/auth/pin/biometric/biometric_screen.dart
> +                _iconBiometricBuilder(isFace),
Назвывай:
_buildIconBiometric.
То есть глагол _build, потом что-то.

2020-10-02 17:21 UTC, merged